name: Testing
on: push

jobs:
  test_project:
    run-on: ubuntu-latest
    steps:
      - users: actions/check
      - name: Run Django unit tests
        run: |
          pip3 install --user django
          python3 manage.py test